### PR TITLE
Feature/rco repo experiment

### PR DESCRIPTION
**Pull request by RonoITU**
I have been testing a little something on a throwaway site today: Creating the database file from scratch during runtime, and executing schema.sql and dump.sql on it. 

See it run on:
https://bdsagroup19chirprazortestersite.azurewebsites.net/

I think this is a good advance for the main branch. We do have to continue work on the repo model. 

This also includes the changes from `feature/issue-90-dbfacade` where the `DBFacade` singleton implementation was looked at and refactored.

### CODE REVIEW

**Comment by RonoITU** [comment]
I am having trouble fixing the test package. This is because this version of DBFacade overwrites DB with `dump.sql`.

**Comment by RonoITU** [comment]
Tests made to work by suppressing SQL executions if those files are missing. Not quite satisfied, but we will move on and refactor to the repository model from here anyway.

**Comment by Spon-art** [comment]
I can vouch for this # closeThisOne

**Review by Spon-art — COMMENTED** [review]
I can vouch for this

**Pull request merged**
