### PR TITLE
User information page and forget me feature

### PR DESCRIPTION
**Pull request by jakso535**
Our program now supports the users access to their data, and right of deletion, in accordance with GDPR.

Tests still need to be applied, but it should be ready to merge to main, and it propably should be, as this branch has lived long enough.

### CODE REVIEW

**Review by NewNorthStar — APPROVED** [review]

**Review by RonoITU — COMMENTED** [review]
I think this is a great start towards solving the session 12 issues. I have two important points that I really want addressed:

- [x] On the final account deletion page, my browser will currently autocomplete my password. This should not happen.
- [ ] Cheeps and follows are objects with clear structured information, rather than attributes added to the Author object. Make the returned JSON reflect this. 

Later some important options to take. Perhaps copy these to another issue:
- [ ] Adding pagination. Imagine hundreds or thousands of interactions and Cheeps.
- [ ] Hiding information behind a "show" button when first landing on the personal data page. Namely the contact information. This is more of a user experience concern: I think it is a trust violation to display this information right away from a navbar click. 
- [ ] We do not know when accounts were created. Should we? If so then for what reason?

**Comment by jakso535** [comment]
> I think this is a great start towards solving the session 12 issues. I have two important points that I really want addressed:
> 
> * [x]  On the final account deletion page, my browser will currently autocomplete my password. This should not happen.
> * [x]  Cheeps and follows are objects with clear structured information, rather than attributes added to the Author object. Make the returned JSON reflect this.
> 
> Later some important options to take. Perhaps copy these to another issue:
> 
> * [ ]  Adding pagination. Imagine hundreds or thousands of interactions and Cheeps.
> * [ ]  Hiding information behind a "show" button when first landing on the personal data page. Namely the contact information. This is more of a user experience concern: I think it is a trust violation to display this information right away from a navbar click.
> * [ ]  We do not know when accounts were created. Should we? If so then for what reason?

Autocomplete has now been turned off, and cheeps and follows are now separate from the author data in the downloaded JSON file

**Comment by jakso535** [comment]
To test these additions futher, we first need to fix our playwright test setup. That will be added as an issue shortly.

**Review by RonoITU — APPROVED** [review]
With advice from https://stackoverflow.com/a/64815833/24573306 I seem to have disabled autofill for the account deletion form. Merge can go ahead.

**Review by Spon-art — APPROVED** [review]
After the chance Ronas made with the autocomplete, I can approve as well. As the rest has been written by Jakob and me.

**Pull request merged**
