### PR TITLE
2a and 2b - SimpleDB using CsvHelper, interface with rest of program. 

### LINKED ISSUE #4: Task 2.a - In order to write and parse cheeps properly, as a dev, i can implement an external CSV library.
Acceptance criteria:
   *   Program can handle ambiguous message inputs.
   *   Cheeps are record objects

### LINKED ISSUE #7: Task 2.b - SimpleDB database as a separate library project.
As a database manager, I want a simple CSV based database for storing cheeps. This will allow us to work on database features separately. 
## Acceptance Criteria
- Project contains a new `classlib` called `SimpleDB`. 
- This database uses a CSV library to store Cheeps. 
- Program should be able to `POST` a Cheep to the DB. 
- Program should be able to `GET` a collection of the Cheeps. 
- The record class `Cheep` is used when transferring data.

### PR DESCRIPTION
**Pull request by RonoITU**
This pull request contains changes to complete feature issues 2a and 2b. It will then be possible to continue with the refactor to complete this weeks project. 
Closes #4. Closes #7.

### CODE REVIEW

**Review by jakso535 — APPROVED** [review]
It looks very good and checks of all acceptance criteria for 2a and 2b, exept as you said a refactoring of program.cs :)

**Comment by llucitu** [comment]
It looks ok

**Review by llucitu — APPROVED** [review]
it looks ok

**Review by Spon-art — APPROVED** [review]
Looking good Ronas. Lets say that 2a and 2b is satisfied

**Pull request merged**
